### ISSUE TITLE
One Pixel Attack

### ISSUE THREAD

**Issue by someshsingh22** [Adversarial-Deep-Learning/code-soup#30]
https://arxiv.org/pdf/1710.08864.pdf
The task list here is as mentioned, 
### Datasets
- [x] Kaggle CIFAR 10
- [x] #35

### Models
- [x] VGG 16
- [x] #37
- [x] #36

### Search (optimization)
- [x] Differential Evolution

**Comment by mehulrastogi** [comment]
The paper uses the following NNs/ datasets that it has used to evaluate the attack:- (checking the ones i plan to implement right now) 
### Datasets
- [x] Kaggle CIFAR 10
- [ ] ImageNet

### Models
- [x] VGG 16
- [ ] NiN
- [ ] All Conv Network

### Search (optimization)
- [x] Differential Evolution

**Comment by someshsingh22** [comment]
Great, I am assigning the remaining subtasks as good first issues.
