### ISSUE TITLE
Minor Improvements in Documentation

### ISSUE THREAD

**Issue by someshsingh22** [Adversarial-Deep-Learning/code-soup#45]
- [x] Cleanup Grammatical Errors
- [x] Update Implementation Readmes
- [x] Change Incorrect Folder Names
- [x] Remove .DS_Stores
- [x] Rename Units
- [x] Add Wiki/Project/Issues/Milestone Details

**Comment by VishalBh4r4mbe** [comment]
In milestones change Unti 2 to Unit 2, ig thats wrong.

**Comment by someshsingh22** [comment]
Thanks for mentioning that @VishalBh4r4mbe
