### ISSUE TITLE
Seeding/Checkpoints for Models / Attacks

### ISSUE THREAD

**Issue by someshsingh22** [Adversarial-Deep-Learning/code-soup#60]
- [ ] Seeding all random variables, random, torch, numpy
- [ ] Save and Load model checkpoints using torch.save

**Comment by soham-chitnis10** [comment]
Hi I would like to take up this issue
My approach :
Function to save a model which takes inputs as model and path with checkpoint to save and function to load from a checkpoint and return the model. Function for seeding all the random variables.

**Comment by someshsingh22** [comment]
@soham-chitnis10 You can take this up however instead of function use classes, and we will also have tensorboards.
