### ISSUE TITLE
Text Datasets

### ISSUE THREAD

**Issue by someshsingh22** [Adversarial-Deep-Learning/code-soup#66]
For Unit 3: We need to start with the text datasets, we will be primarily using torchtext.
We need the following:

- [x] Torchtext predefined datasets
- [x] SNLI
- [x] SST

**Comment by aneesha17** [comment]
I'll take up this issue.

**Comment by someshsingh22** [comment]
Great @aneesha17 you can take this up

**Comment by someshsingh22** [comment]
SNLI, SST have been ported in current Torchtext module
